name: clang-format
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  formatting-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '18'
        exclude-regex: '(tests\/catch_*.*pp|benchmarks\/catch_*.*pp)'
        include-regex: '(include\/hpcombi\/*.hpp|tests\/*.cpp|benchmarks\/*.cpp|examples\/*.cpp|examples\/*.h)'
